version: 2.1
orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@1.2

workflows:
  # Below is the definition of your workflow.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  version: 2
  build-test-approve-deploy:
    jobs:
      - heroku/deploy-via-git:
          force: true # this parameter instructs the push to use a force flag when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git
          filters:
            branches:
              # This sample config runs this job on any branch matching the regex below, however, it's more likely you want to only run this job on master.
              # only: /.*-heroku-deploy/ # Delete this line
              only: develop # Uncomment this line
